# Generated by Django 5.1.2 on 2024-12-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_cart_cartitem_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='uniform',
            new_name='uniform_name',
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='Medium', max_length=50),
        ),
    ]
